const parent_child = {
    "CHILD_ONE" : "CHILD_ONE",
    "CHILD_TWO" : "CHILD_TWO",
    "CHILD_THREE" : "CHILD_THREE",
    "CHILD_FOUR" : "CHILD_FOUR",
    "PARENT_TRIGGER_CHILD1" : "PARENT_TRIGGER_ON_CHILD1_CHANGE",
    "PARENT_TRIGGER_SCORE" : "PARENT_TRIGGER_ON_SCORE_CHANGE",
    "PARENT_TRIGGER_TEAM" : "PARENT_TRIGGER_ON_TEAM_CHANGE"
  } 
  
  export default parent_child;